apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /mnt/azure  # Where to access the storage inside the pod
      name: azure-storage
  volumes:
  - name: azure-storage
    persistentVolumeClaim:
      claimName: azure-managed-disk  # Refers to the PVC we created earlier
